name: alla_romana
description: Divide costs with your friends

publish_to: "none"

version: 1.0.1+2

environment:
    sdk: ">=2.18.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    intl: ^0.17.0
    decimal: ^2.3.2
    dynamic_color: ^1.5.4
    awesome_dialog: ^3.0.2
    cupertino_icons: ^1.0.2
    currency_formatter: ^2.0.0
    shared_preferences: ^2.0.15
    appinio_social_share: ^0.2.0
    flutter_launcher_icons: ^0.11.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    generate: true

flutter_intl:
    enabled: true
    class_name: AppLocalizations

flutter_icons:
    android: true
    image_path: "assets/logo.png"
    adaptive_icon_foreground: "assets/logo.png"
    adaptive_icon_background: "#8E001C"
