name: Build APK

on:
    push:
        branches:
            - main

env:
    JAVA_VERSION: "12.x"
    FLUTTER_VERSION: "3.3.10"
    FLUTTER_CHANNEL: "stable"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: ${{env.JAVA_VERSION}}
            - uses: subosito/flutter-action@v1
              with:
                  channel: ${{ env.FLUTTER_CHANNEL }}
                  flutter-version: ${{ env.FLUTTER_VERSION }}

            - name: Generate key.properties from secrets
              run: echo "${{ secrets.KEY_PROPERTIES }}" | base64 -d > android/key.properties

            - name: Generate key.jks from secrets
              run: echo ${{ secrets.KEY_JKS }} | base64 -di > android/key.jks

            - name: Build apk
              run: flutter pub get && flutter build apk --release

            - uses: actions/upload-artifact@v2
              with:
                  name: release-apk
                  path: build/app/outputs/apk/release/app-release.apk
